### ISSUE TITLE
mutagen directory doesn't exist

### ISSUE THREAD

**Issue by Wikunia** [BenOckmore/mutagen#28]
I never installed a library in Python before, so don't know if it's the right way...
I am using Python 3.4 (inside C:\Python) 

```
 C:\Python34>python Lib/mutagen/setup.py build
running build
running build_py
error: package directory 'mutagen' does not exist
```

**Comment by BenOckmore** [comment]
Hi - are you using the master branch or one of the release branches (mutagenx1.xx), or a download from PyPI? What steps have you run prior to the "build" command?

I usually get all of my packages with pip, so haven't done much installing using setup.py before. However, if I do the following commands straight after downloading, it seems to work (on Linux - you may need to adjust the syntax slightly for Windows):

```
cd mutagen
./setup.py build
./setup.py install
```

So I think the issue is just that you need to run the setup.py script from the right directory, so that it can locate the mutagen package. I believe you could also miss out the build step, and just run ./setup.py install. That will (I think) move the package modules into your Python distribution.

Let me know if any of this works for you!

**Comment by Wikunia** [comment]
Oh perfect!
Thanks everything works fine now. Changed directly into the directory and only used install :)
