### ISSUE TITLE
Easy option is missing the rating tags for mp3

### ISSUE THREAD

**Issue by jgandert** [BenOckmore/mutagen#31]
I opened the same file once normally and then with the `easy` option, but it didn't show the rating. (Although it worked for another FLAC file I tested.)

``` python
>>> f1 = m.File('./Little Inferno/16 - Productivity Tango.mp3')
>>> f2 = m.File('./Little Inferno/16 - Productivity Tango.mp3', easy=True)
>>> print(f1.pprint())
MPEG 1 layer 3, 160000 bps, 44100 Hz, 56.32 seconds (audio/mp3)
APIC= (image/jpeg, 48206 bytes)
COMM=='deu'=LittleInferno.com
COMM=='eng'=LittleInferno.com
POPM=Banshee=None 1/255
TALB=Little Inferno Original Soundtrack
TCON=Other
TDRC=2012
TIT2=Productivity Tango
TPE1=Kyle Gabler
TPE2=Kyle Gabler
>>> print(f2.pprint())
MPEG 1 layer 3, 160000 bps, 44100 Hz, 56.32 seconds (audio/mp3)
album=Little Inferno Original Soundtrack
artist=Kyle Gabler
date=2012
genre=Other
performer=Kyle Gabler
title=Productivity Tango
```

Anyway, thanks for porting this library to Python 3! :+1:

**Comment by jgandert** [comment]
I have a side question: What is the difference / meaning of these versions?:
`:` — `RATING:BANSHEE=1.0` (this is from the FLAC file that worked)
`=` (the first one) — `POPM=Banshee=None 1/255` - 
`==` — `COMM=='deu'=LittleInferno.com`

Shouldn't the all use the same character to delimit the key (e.g. Banshee) from the "tag" and the value.

**Comment by BenOckmore** [comment]
From the looks of it, rating isn't one of the currently supported frames for EasyID3 - I think that you might be better opening this issue on the original mutagen project rather than my port here.

As for your second question, I guess that it's just differences in the way the tags are being printed between different formats. Although it's interesting that COMM has a double equals, that doesn't seem to fit with the rest of the output - I'll investigate.

**Comment by jgandert** [comment]
Okay I [reported it there](https://bitbucket.org/lazka/mutagen/issue/185). I think `:` looks the best and least confusing. (e.g. `rating:banshee=0.75`)

**Comment by BenOckmore** [comment]
Closing this here, as it applies to mutagen too and an issue has been filed on the bitbucket page.
